version: "2"
services:
  php-5.5:
    image: damabox_php55:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/5.5/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      connect:
        ipv4_address: 10.5.0.5

  php-5.6:
    image: damabox_php56:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/5.6/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      connect:
        ipv4_address: 10.5.0.6

  php-7.0:
    image: damabox_php70:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/7.0/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      connect:
        ipv4_address: 10.5.0.7

  php-7.1:
    image: damabox_php71:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/app
      - ./config/php/7.1/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      connect:
        ipv4_address: 10.5.0.8

  nginx:
    image: damabox_nginx:latest
    restart: always
    ports:
     - "${HTTP_PORT}:80"
    volumes:
     - ./config/nginx/servers:/etc/nginx/sites-available
     - ${PROJECT_DIR}:/app
    networks:
      connect:
        ipv4_address: 10.5.0.9

  firebird:
    image: damabox_firebird:latest
    restart: always
    environment:
      - FIREBIRD_USER=${FIREBIRD_ROOT_USER}
      - FIREBIRD_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
      - ISC_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
    ports:
      - "${FIREBIRD_PORT}:3050"
    volumes:
      - ${FIREBIRD_DATADIR}:/databases
    networks:
      connect:
        ipv4_address: 10.5.0.10

networks:
  connect:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
