version: "2"
services:
  apache:
    image: dunasplus_php_apache:latest
    restart: always
    ports:
     - "${HTTP_PORT}:80"
    volumes:
     - ${PROJECT_DIR}:/var/www/site/app
    links:
      - firebird

  firebird:
    image: dunasplus_firebird:latest
    restart: always
    environment:
      - FIREBIRD_USER=${FIREBIRD_ROOT_USER}
      - FIREBIRD_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
      - ISC_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
    ports:
      - "${FIREBIRD_PORT}:3050"
    volumes:
      - ${FIREBIRD_DATADIR}:/databases
