version: "2"
services:
  apache:
    image: dunasplus_php_apache:latest
    restart: always
    ports:
     - "${HTTP_PORT}:80"
    volumes:
     - ${PROJECT_DIR}:/var/www/site/app
    networks:
      connect:
        ipv4_address: 10.5.0.5

  firebird:
    image: dunasplus_firebird:latest
    restart: always
    environment:
      - FIREBIRD_USER=${FIREBIRD_ROOT_USER}
      - FIREBIRD_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
      - ISC_PASSWORD=${FIREBIRD_ROOT_PASSWORD}
    ports:
      - "${FIREBIRD_PORT}:3050"
    volumes:
      - ${FIREBIRD_DATADIR}:/databases
    networks:
      connect:
        ipv4_address: 10.5.0.6

networks:
  connect:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
